#!/usr/bin/env python3

from fetch_items import fetch_items, get_formated_headers_and_texts
from display_heb_on_term import display_rtl_on_terminal

RTL_START = u'\u202B'
RTL_END = u'\u202C'


def print_text(user_input, texts):
    def p(item_num):
        i = int(item_num.strip())-1
        display_rtl_on_terminal(texts[i])
    if "," in user_input:
        for item_num in user_input.split(","):
            p(item_num)
        exit()
    p(user_input)
    return
    
    
def fetch_and_display_headers():
    formated_headers, formated_texts = get_formated_headers_and_texts(enumerate=True)
    for header in formated_headers:
        print(header)
    return formated_texts

# Fetch all data, display headers and get full texts
texts = fetch_and_display_headers()

# Interact with the user
print("Commands: Num of item, numbers seprated by commas,'Enter' to referesh or q to exit")
prompt = " > "
ans = input(prompt)
while True:
    match ans:
        case "q":
            exit()
        case "":
            texts = fetch_and_display_headers()        
        case _:
            print_text(ans, texts)
    ans = input(prompt)
