def generate_terms_iterations_file():
    # Genrate the lists of head-nouns and end-nouns
    head_nouns = []
    end_nouns = []
    stand_alone_nouns = []
    for l in open("terms_to_exclude.txt").read().split("\n"):
        l = l.strip()
        if l=="": continue
        head_noun = ""; end_noun = ""; stand_alone_noun = ""
        ll = l.split()
        #print(ll)
        if len(ll)>=3 and "של" in ll:
            sep_index = ll.index("של")    
            head_noun = " ".join(ll[:sep_index])
            end_noun = " ".join(ll[sep_index+1:])
        elif len(ll)>1 and (ll[1][0]=="ה" or ll[1][0]=="ל"):
            head_noun = ll[0]
            ll[1] = ll[1][1:] 
            end_noun = " ".join(ll[1:])
        else:
            stand_alone_noun = l

        if stand_alone_noun:
            if not stand_alone_noun in stand_alone_nouns:
                 stand_alone_nouns.append(stand_alone_noun)
            #print("    stand alone:", stand_alone_noun)
        if head_noun:
            if not head_noun in head_nouns:
                 head_nouns.append(head_noun)
            #print("    head:", head_noun)
        if end_noun:
            if not end_noun in end_nouns:
                 end_nouns.append(end_noun)
            #print("     end:", end_noun)
        #print()

    # Generate the full file w/all itterations of the terms
    of = open("autogenerated_terms_to_exclude.txt", 'w')
    for noun in stand_alone_nouns:
        of.write(noun+"\n")
    of.write("\n")
    for head_noun in head_nouns:
        for end_noun in end_nouns:
            of.write(f"{head_noun} של {end_noun}\n")
            if not end_noun.startswith("ה"):
                of.write(f"{head_noun} ה{end_noun}\n")
                of.write(f"{head_noun} ל{end_noun}\n")
if __name__=="__main__":
    generate_terms_iterations_file()
